// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/nacos-group/nacos-sdk-go/clients"
	kamacache "github.com/zuozikang/cache"
)

// Injectors from wire.go:

// InitializeApp 初始化
func InitializeApp(addr string) (*App, error) {
	server, err := ProvideServer(addr)
	if err != nil {
		return nil, err
	}
	v := kamacache.DefaultPickerOptions()
	clientPicker, err := kamacache.NewClientPicker(addr, v...)
	if err != nil {
		return nil, err
	}
	group := ProvideGroup()
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	nacosClientParam, err := ProvideNacosClientParam(config)
	if err != nil {
		return nil, err
	}
	iConfigClient, err := clients.NewConfigClient(nacosClientParam)
	if err != nil {
		return nil, err
	}
	app := NewApp(server, clientPicker, group, iConfigClient)
	return app, nil
}

// wire.go:

// AppSet 依赖
var AppSet = wire.NewSet(
	NewApp,
)

// 绑定接口和实现类
var PickerSet = wire.NewSet(kamacache.NewClientPicker, kamacache.DefaultPickerOptions, wire.Bind(new(kamacache.PeerPicker), new(*kamacache.ClientPicker)))

// ProviderSet 依赖
var ProviderSet = wire.NewSet(
	ProvideServer,
	ProvideGroup,
)

// nacosClientSet 依赖
var nacosClientSet = wire.NewSet(
	ProvideNacosClientParam, clients.NewConfigClient,
)
